steps:
    -
        name: gcr.io/cloud-builders/docker
        args:
            - build
            - '-t'
            - 'asia.gcr.io/$PROJECT_ID/crud-op:cloudbuild-dev-$BRANCH_NAME-$SHORT_SHA'
            - .
    -
        name: gcr.io/cloud-builders/docker
        args:
            - tag
            - 'asia.gcr.io/$PROJECT_ID/crud-op:cloudbuild-dev-$BRANCH_NAME-$SHORT_SHA'
            - 'asia.gcr.io/$PROJECT_ID/crud-op:cloudbuild-dev-$BRANCH_NAME-latest'
    -
        name: gcr.io/cloud-builders/gcloud
        args:
            - beta
            - run
            - deploy
            - crud-op-dev
            - '--image'
            - 'asia.gcr.io/$PROJECT_ID/crud-op:cloudbuild-dev-$BRANCH_NAME-latest'
            - '--region'
            - us-central1
            - '--platform'
            - managed
            - '--allow-unauthenticated'
images:
    - 'asia.gcr.io/$PROJECT_ID/crud-op:cloudbuild-dev-$BRANCH_NAME-$SHORT_SHA'
    - 'asia.gcr.io/$PROJECT_ID/crud-op:cloudbuild-dev-$BRANCH_NAME-latest'
